In [1]:
import torch

In [2]:
torch.Tensor([1,2,3])

tensor([1., 2., 3.])

In [3]:
import numpy as np

In [4]:
array1 = np.arange(12).reshape(3, 4)

In [5]:
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
torch.Tensor(array1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])